"""Test candidate discovery filters and the two provenance-merge entry points.

``merge_candidates`` folds the proximity and declaration passes together and
``deduplicate_special_position_contacts`` collapses near-coincident symmetry
images; the two have deliberately opposite ownership contracts, which is
asserted here. Fixtures are synthetic and need neither CCP4 nor the network.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import gemmi
import helpers
import pytest
from helpers import AtomSpec, approx, simple_metal_site

import codes
import structure_analysis as sa
from coordination import candidates, policy
from coordination.contact_record import (
    Candidate,
    DeclaredConnectionRecord,
    DonorPolicy,
    EligibilityResult,
)
from coordination.donor_chemistry import DONOR_ELEMENTS
from metal_elements import METAL_ELEMENTS

# Two coordinates of one image that straddle the fifth decimal place. The
# declared route (``fract_image``/``orthogonalize``) and the proximity route
# (``find_nearest_pbc_position``) differ in the last bits like this, so a
# rounded identity key put one physical contact in two buckets.
ROUNDING_BOUNDARY = 2.000005
IMAGE_NOISE = 1e-12


def _neighbor(atom_index: int = 0) -> sa.AtomSite:
    """One deposited water record, as ``load_structure`` would report it."""
    return helpers.atom_site(
        "O",
        atom_name="O",
        residue_name="HOH",
        is_water=True,
        source_order=atom_index,
    )


def _image(
    x: float,
    *,
    symmetry: bool = True,
    translation: tuple[int, int, int] = (0, 0, 0),
    distance: float = 2.0,
) -> sa.ContactImage:
    """A contact image at ``(x, 0, 0)``, symmetry-generated by default."""
    return sa.ContactImage(
        distance=distance,
        position=(x, 0.0, 0.0),
        crystallographic_contact=symmetry,
        strict_ncs_contact=False,
        strict_ncs_operation_id="",
        scope=(
            codes.ContactScope.CRYSTALLOGRAPHIC
            if symmetry
            else codes.ContactScope.EXPLICIT
        ),
        image_index=int(symmetry),
        symmetry_operation="2_555" if symmetry else "1_555",
        translation=translation,
    )


def _declaration(connection_id: str = "metalc1") -> DeclaredConnectionRecord:
    """One declaration provenance record, as declaration resolution writes it."""
    return DeclaredConnectionRecord(
        source=codes.CandidateSource.STRUCT_CONN,
        connection_id=connection_id,
        connection_type="metalc",
        connection_link_id="",
        connection_asu="same",
        connection_reported_distance=2.0,
    )


def _proximity(
    image: sa.ContactImage, neighbor: sa.AtomSite | None = None
) -> Candidate:
    """A candidate as proximity discovery emits it: no metal, no declaration."""
    return Candidate(
        neighbor=_neighbor() if neighbor is None else neighbor,
        image=image,
        candidate_sources={codes.CandidateSource.PROXIMITY_4A},
    )


def _declared(
    image: sa.ContactImage,
    *,
    connection_id: str = "metalc1",
    neighbor: sa.AtomSite | None = None,
) -> Candidate:
    """A candidate as declaration resolution emits it, carrying its record."""
    return Candidate(
        neighbor=_neighbor() if neighbor is None else neighbor,
        image=image,
        candidate_sources={codes.CandidateSource.STRUCT_CONN},
        declared_connections=[_declaration(connection_id)],
    )


def test_both_position_routes_of_one_image_merge_across_a_bucket_edge() -> None:
    """A last-bit difference may not split one contact into two candidate rows.

    The declaration and proximity routes to the same symmetry image differ by
    about 1e-12 A. Bucketing the position by ``round(value, 5)`` separated the
    two whenever they straddled a bucket edge, publishing the same physical
    contact twice with the provenance split between the rows.
    """
    low = ROUNDING_BOUNDARY - IMAGE_NOISE
    high = ROUNDING_BOUNDARY + IMAGE_NOISE
    assert round(low, 5) != round(high, 5)
    assert sa.position_distance((low, 0.0, 0.0), (high, 0.0, 0.0)) == approx(
        2 * IMAGE_NOISE, abs=1e-15
    )

    merged = candidates.merge_candidates(
        [_proximity(_image(low))], [_declared(_image(high))]
    )

    assert len(merged) == 1
    assert merged[0].candidate_sources == {
        codes.CandidateSource.PROXIMITY_4A,
        codes.CandidateSource.STRUCT_CONN,
    }
    assert [record.connection_id for record in merged[0].declared_connections] == [
        "metalc1"
    ]
    # First seen wins, so the retained position is the proximity route's.
    assert merged[0].image.position[0] == low


def test_three_near_coincident_images_of_one_atom_collapse_to_one_candidate() -> None:
    """Every candidate in a noise-sized cluster joins the first one seen."""
    positions = [
        ROUNDING_BOUNDARY - IMAGE_NOISE,
        ROUNDING_BOUNDARY,
        ROUNDING_BOUNDARY + IMAGE_NOISE,
    ]
    merged = candidates.merge_candidates(
        [_proximity(_image(positions[0]))],
        [_declared(_image(positions[1]), connection_id="metalc1")],
        [_declared(_image(positions[2]), connection_id="metalc2")],
    )

    assert len(merged) == 1
    assert merged[0].image.position[0] == positions[0]
    assert sorted(
        record.connection_id for record in merged[0].declared_connections
    ) == ["metalc1", "metalc2"]


def test_a_resolvable_displacement_within_one_image_stays_two_candidates() -> None:
    """The merge tolerance covers arithmetic noise, not a real separation.

    0.01 A is four orders of magnitude above the tolerance: two records that
    far apart are not the same atom image and must stay separately reported.
    """
    merged = candidates.merge_candidates(
        [_proximity(_image(2.0))], [_declared(_image(2.01))]
    )

    assert len(merged) == 2


@pytest.mark.parametrize(
    ("first", "second"),
    [
        (_image(2.0, translation=(0, 0, 0)), _image(2.0, translation=(1, 0, 0))),
        (_image(2.0, symmetry=False), _image(2.0, symmetry=True)),
    ],
    ids=["translation", "symmetry_operation"],
)
def test_images_from_different_operations_are_never_merged(
    first: sa.ContactImage, second: sa.ContactImage
) -> None:
    """Grouping is by operation and lattice translation, not position alone.

    Two lattice images can land on the same point only through noise in the
    same operation; a different operation or translation is a different image
    even where the coordinates coincide.
    """
    merged = candidates.merge_candidates([_proximity(first)], [_declared(second)])

    assert len(merged) == 2


def test_different_source_atoms_at_one_point_are_never_merged() -> None:
    """Two deposited records are two candidates however close they sit."""
    merged = candidates.merge_candidates(
        [_proximity(_image(2.0), neighbor=_neighbor(atom_index=0))],
        [_declared(_image(2.0), neighbor=_neighbor(atom_index=1))],
    )

    assert len(merged) == 2


def test_merge_keeps_the_declaration_provenance_in_either_arrival_order() -> None:
    """A declaration's provenance survives a merge whichever route arrives first.

    Proximity discovery and declaration resolution reach the same image, and
    the merged record must carry both sources and the declaration record no
    matter which group was scanned first.
    """
    expected = {codes.CandidateSource.PROXIMITY_4A, codes.CandidateSource.STRUCT_CONN}

    proximity_first = candidates.merge_candidates(
        [_proximity(_image(2.0))], [_declared(_image(2.0))]
    )
    declared_first = candidates.merge_candidates(
        [_declared(_image(2.0))], [_proximity(_image(2.0))]
    )

    for merged in (proximity_first, declared_first):
        assert len(merged) == 1
        assert merged[0].candidate_sources == expected
        assert [record.connection_id for record in merged[0].declared_connections] == [
            "metalc1"
        ]


def test_merge_candidates_copies_and_leaves_the_caller_records_untouched() -> None:
    """``merge_candidates`` owns its output; the inputs are never mutated.

    It runs before the annotation stages precisely because it copies: the
    stage results are ``init=False`` and would be dropped by the copy.
    """
    proximity = _proximity(_image(2.0))
    declared = _declared(_image(2.0))

    merged = candidates.merge_candidates([proximity], [declared])

    assert len(merged) == 1
    assert merged[0] is not proximity
    assert merged[0] is not declared
    assert proximity.candidate_sources == {codes.CandidateSource.PROXIMITY_4A}
    assert proximity.declared_connections == []
    assert declared.candidate_sources == {codes.CandidateSource.STRUCT_CONN}


def test_deduplicate_special_position_contacts_merges_into_the_caller_records() -> None:
    """The collapse mutates and returns the caller's own annotated candidates.

    It runs after eligibility annotation, so it must not copy: a copy would
    reset the stage results that the bond rows are then built from.
    """
    retained = _proximity(_image(0.0, symmetry=False))
    coincident = _declared(_image(0.4))

    collapsed = candidates.deduplicate_special_position_contacts([retained, coincident])

    assert len(collapsed) == 1
    assert collapsed[0] is retained
    assert retained.candidate_sources == {
        codes.CandidateSource.PROXIMITY_4A,
        codes.CandidateSource.STRUCT_CONN,
    }
    assert [record.connection_id for record in retained.declared_connections] == [
        "metalc1"
    ]
    assert coincident.declared_connections[0] in retained.declared_connections


def _context_and_search(
    builder: helpers.StructureBuilder, path: Path
) -> tuple[sa.StructureContext, gemmi.NeighborSearch, sa.AtomSite]:
    """Load ``builder`` and return its context, explicit search, and one metal."""
    written = helpers.write_pdb(builder.to_gemmi(), path)
    context = sa.load_structure("test", written)
    search = context.make_neighbor_search(
        policy.CANDIDATE_SEARCH_RADIUS + policy.SEARCH_EPSILON,
        include_symmetry=False,
        positive_occupancy_only=True,
    )
    metals = context.metal_atoms(METAL_ELEMENTS, canonical=True)
    assert len(metals) == 1
    return context, search, metals[0]


def _atom_names(found: Sequence[Candidate]) -> list[str]:
    return sorted(candidate.neighbor.atom_name for candidate in found)


def test_a_metal_without_finite_coordinates_has_no_candidates(tmp_path: Path) -> None:
    """A malformed metal record is never handed to the spatial search."""
    context, search, _ = _context_and_search(simple_metal_site(), tmp_path / "nan.pdb")
    broken = helpers.atom_site(
        "ZN",
        atom_name="ZN",
        residue_name="ZN",
        pos=(float("nan"), float("nan"), float("nan")),
    )
    assert not broken.coordinates_valid

    assert candidates.collect_proximal_candidates(context, search, broken, False) == []


def test_a_mark_outside_the_selected_model_is_skipped(tmp_path: Path) -> None:
    """A mark that resolves to no selected atom is dropped, not crashed on.

    A caller-supplied search may be binned over atoms this analysis never
    selected, so discovery must tolerate a mark it cannot resolve.
    """
    context, search, metal = _context_and_search(
        simple_metal_site(), tmp_path / "ghost.pdb"
    )
    expected = _atom_names(
        candidates.collect_proximal_candidates(context, search, metal, False)
    )

    ghost = gemmi.Atom()
    ghost.name = "GST"
    ghost.element = gemmi.Element("O")
    ghost.pos = gemmi.Position(2.2, 0.0, 0.0)
    ghost.occ = 1.0
    search.add_atom(ghost, 99, 99, 99)
    assert context.atom_for_indices(99, 99, 99) is None

    found = candidates.collect_proximal_candidates(context, search, metal, False)

    assert _atom_names(found) == expected
    assert "GST" not in _atom_names(found)


def test_discovery_rejects_non_donors_foreign_residues_and_the_metal_itself(
    tmp_path: Path,
) -> None:
    """Only donor-element atoms of waters and amino acids, at a real distance.

    Four rejections are exercised at once because each needs the same loaded
    structure: a carbon in range, a donor in a residue that is neither water
    nor an amino acid, and a donor superimposed on the metal, alongside the
    histidine nitrogen that must survive all three filters.
    """
    builder = simple_metal_site(donors=[("HIS", "NE2", 2.03)])
    # A side-chain carbon well inside the search radius: donor elements are
    # N, O and S, so this is rejected on element alone.
    builder.add_amino_acid(
        "ALA",
        30,
        chain="A",
        positions={"CB": (3.0, 0.0, 0.0)},
        origin=(40.0, 40.0, 40.0),
    )
    # A donor oxygen in a residue that is neither water nor an amino acid.
    builder.add_hetero_residue(
        "EDO", 200, [AtomSpec(name="O1", element="O", pos=(0.0, 2.2, 0.0))], chain="B"
    )
    # A water modeled on top of the metal: distance 0.0 is excluded by the
    # open lower bound, which also excludes the metal's own record.
    builder.add_water(300, (0.0, 0.0, 0.0), chain="B")

    context, search, metal = _context_and_search(builder, tmp_path / "filters.pdb")
    found = candidates.collect_proximal_candidates(context, search, metal, False)

    assert _atom_names(found) == ["NE2"]
    assert all(candidate.neighbor.element in DONOR_ELEMENTS for candidate in found)
    assert all(candidate.image.distance > 0.0 for candidate in found)
    # The rejected atoms really were inside the radius that was searched.
    in_range = {
        atom.atom_name
        for atom in context.contact_atoms
        if sa.position_distance(atom.xyz, metal.xyz) <= policy.CANDIDATE_SEARCH_RADIUS
    }
    assert {"CB", "O1"} <= in_range


def _annotate_as_inferred(candidate: Candidate) -> None:
    """Attach the verdicts an inferred-eligible water donor would receive."""
    candidate.set_donor_policy(
        DonorPolicy(
            inferred_allowed=True,
            rule=codes.InferredDonorRule.WATER_OXYGEN,
            override="",
        )
    )
    candidate.set_eligibility(
        EligibilityResult(
            status=codes.EligibilityStatus.FIRST_SPHERE_ELIGIBLE,
            reason=codes.EligibilityReason.DISTANCE_WITHIN_TOLERANCE,
            first_sphere_eligible=True,
            inferred_contact_eligible=True,
            assignment_target=2.09,
            assignment_tolerance=policy.FIRST_SPHERE_TOLERANCE,
            first_sphere_cutoff=2.84,
            assignment_reference_kind=codes.ReferenceKind.EXACT,
            assignment_reference="HOH:O:ZN",
        )
    )


def test_adding_provenance_after_annotation_is_refused() -> None:
    """``add_provenance`` is the pre-annotation entry point and says so.

    Donor policy and eligibility read the provenance once. A merge that
    arrives afterwards would be invisible to the verdicts already recorded, so
    the ordinary entry point refuses it rather than merging silently.
    """
    retained = _proximity(_image(2.0))
    _annotate_as_inferred(retained)

    with pytest.raises(RuntimeError, match="after the donor-policy stage"):
        retained.add_provenance(_declared(_image(2.0)))

    assert retained.candidate_sources == {codes.CandidateSource.PROXIMITY_4A}
    assert retained.declared_connections == []


def test_post_annotation_collapse_does_not_disturb_the_recorded_verdicts() -> None:
    """The special-position collapse adds provenance without changing a verdict.

    ``deduplicate_special_position_contacts`` runs after eligibility, so it
    merges through ``merge_provenance_after_annotation``. This pins the safety
    argument that method documents: the verdicts already recorded are the same
    objects afterwards, and re-running either stage is still refused.
    """
    retained = _proximity(_image(0.0, symmetry=False))
    coincident = _declared(_image(0.4))
    for candidate in (retained, coincident):
        _annotate_as_inferred(candidate)
    donor_policy_before = retained.donor_policy()
    eligibility_before = retained.eligibility()

    collapsed = candidates.deduplicate_special_position_contacts([retained, coincident])

    assert collapsed == [retained]
    assert retained.donor_policy() is donor_policy_before
    assert retained.eligibility() is eligibility_before
    # The provenance did grow, and it is what the published columns read.
    assert retained.candidate_sources == {
        codes.CandidateSource.PROXIMITY_4A,
        codes.CandidateSource.STRUCT_CONN,
    }
    assert len(retained.declared_connections) == 1
    # The stages stay one-shot: nothing may re-derive a verdict from the
    # provenance the collapse added.
    with pytest.raises(RuntimeError, match="donor policy was already evaluated"):
        retained.set_donor_policy(donor_policy_before)
